### ISSUE TITLE
4.1.2 Fails on yarn build in typescript

### ISSUE THREAD

**Issue by GeorgeStoianTP** [MatthD/node-libxml#14]
I've included this package in my project and when I try to build it I get the following error:
```
node_modules/node-libxml/index.d.ts:172:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.

export = Libxml;
```
I've reverted to 4.1.1 which doesn't have declaration files and that works fine.

**Comment by MatthD** [comment]
Hi @GeorgeStoianTP , what version of typescript do you use in your project ?

Do you find a solution?

**Comment by MatthD** [comment]
I corrected some TS files, let's see if the error happen again in the V5.0.0
