### ISSUE TITLE
Node-libxml crashes inside docker container

### ISSUE THREAD

**Issue by vBitza** [MatthD/node-libxml#25]
Hi,

I'm currently having some weird issue while using node-libxml inside a Docker container, it just crashes the container without any errors at all.

node-libxml version: 4.1.2
node-version: 16.14
docker image: node:16.14.0-alpine3.15

It seems it crashes when loading an invalid (not well-structured) XML file:

    const xmlFileContent = Buffer.from(req.files[0].buffer)
      .toString();
    xmlIsWellformed = libxml.loadXmlFromString(xmlFileContent);

**Comment by thomas-kerfy** [comment]
Hi !

I had the same problem with Docker and `node-libxml@4.1.0`, I managed to solve it by adding these lines in my Dockerfile during the build :

```
RUN npm run build && ( \
	cd node_modules/node-libxml && \
	/src/node_modules/.bin/prebuildify --napi -t "$(node --version | tr -d v)" \
	)
```

Hope it works for you ;)

**Comment by MatthD** [comment]
I created V5.0.6, with more arch for platforms
