### ISSUE TITLE
No valid version for napi

### ISSUE THREAD

**Issue by ELBEQQAL94** [MatthD/node-libxml#26]
I am trying to install node-libxml on my machine but I got this error: No valid version for napi

OS: Windows 10
Node: v8.16.2
npm: 6.4.1
node-libxml: ^3.2.5

Any suggestions or help please

Thanks

**Comment by Nagyjano** [comment]
If you can use newer node version than you can try with the latest node-libxml version as well.
Older versions of node-libxml tightly coupled with node internal js implementation namely V8 so they are really sensitive about node version.
