### ISSUE TITLE
Possibility of reducing package size?

### ISSUE THREAD

**Issue by db798** [MatthD/node-libxml#34]
Hi, is there any possibility to reduce the size of this package, from what I can tell it adds ~100MB to the size of my node_modules folder. Not sure if everything is actually needed, maybe it is, just want to verify.

Below is a list of node_modules over 1MB in my project, most are irrelevant but please note that typescript is not listed.
<img width="772" alt="node_modules_without_this_package" src="https://github.com/user-attachments/assets/a51242bb-4c9f-48c7-8643-e9f5470eee6a">

After installing, typescript goes to ~66MB and node-libxml is also ~40MB.
<img width="773" alt="node_modules_after_installing_this_package" src="https://github.com/user-attachments/assets/996b9292-5fd0-4759-a794-7df2b88e7703">

_Note: the before includes `libxmljs2` which I'm trying to move away from._

Is there anything that could be done about this? Does typescript actually need to be a dependency, could it be a devDependency? Is there a way to only install specific pre-builds, each one is ~1.4MB but I probably only need one of them.

For some context I'm trying to use this package in a lambda but because this package is so large the lambda is exceeding the allowed size.

**Comment by polomsky** [comment]
For windows, I was able to reduce node_modules usage from 107MB to 19.7MB.
